

module.exports = {
    SHIP_QUERY: [
        'SELECT',
            'typeID,',
            'typeName,',
            'invTypes.description,',
            'invGroups.groupName',
        'FROM',
            'invTypes,',
            'invGroups',
        'WHERE',
            'invTypes.groupID == invGroups.groupID',
            'AND invGroups.categoryID = 6',
            'AND typeName LIKE $typeName'
    ].join(' '),
    ATTRIBUTE_QUERY: [
        'SELECT',
            'dgmAttributeTypes.attributeID,',
            'dgmAttributeTypes.attributeName,',
            'dgmAttributeTypes.displayName,',
            'dgmAttributeTypes.published,',
            'dgmTypeAttributes.attributeID,',
            'dgmTypeAttributes.typeID,',
            'dgmTypeAttributes.value',
        'FROM',
            'dgmAttributeTypes,',
            'dgmTypeAttributes',
        'WHERE',
           'dgmAttributeTypes.attributeID = dgmTypeAttributes.attributeID',
           'AND published = 1',
           'AND dgmTypeAttributes.typeID = $typeId'
    ].join(' '),
        
    SKILL_QUERY: [
        'SELECT',
            'Skills.typeName AS skillName,',
            'SkillName.value AS skillId,',
            'SkillLevel.value AS requiredLevel',
        'FROM',
            'invTypes AS Skills,',
            'dgmTypeAttributes AS SkillName,',
            'dgmTypeAttributes AS SkillLevel',
        'WHERE',
            'Skills.typeID == SkillName.value',
            'AND (',
                'SkillName.attributeID == 182  OR',
                'SkillName.attributeID == 183  OR',
                'SkillName.attributeID == 184  OR',
                'SkillName.attributeID == 1285 OR',
                'SkillName.attributeID == 1289 OR',
                'SkillName.attributeID == 1290',
            ')',
            'AND SkillLevel.typeID == SkillName.typeID',
            'AND (',
                'SkillLevel.attributeID == 277  OR',
                'SkillLevel.attributeID == 278  OR',
                'SkillLevel.attributeID == 279  OR',
                'SkillLevel.attributeID == 1286 OR',
                'SkillLevel.attributeID == 1287 OR',
                'SkillLevel.attributeID == 1288',
            ')',
            'AND (',
                '(SkillName.attributeID == 182  AND SkillLevel.attributeID == 277 ) OR',
                '(SkillName.attributeID == 183  AND SkillLevel.attributeID == 278 ) OR',
                '(SkillName.attributeID == 184  AND SkillLevel.attributeID == 279 ) OR',
                '(SkillName.attributeID == 1285 AND SkillLevel.attributeID == 1286) OR',
                '(SkillName.attributeID == 1289 AND SkillLevel.attributeID == 1287) OR',
                '(SkillName.attributeID == 1290 AND SkillLevel.attributeID == 1288)',
            ')',
            'AND SkillName.typeID == $typeId'
    ].join(' ')
};