

module.exports = {
    ITEM_ID_QUERY: [
        'SELECT',
            'typeID AS id,',
            'typeName AS name,',
            'invTypes.description,',
            'invGroups.groupName AS type,',
            'invCategories.categoryName AS category,',
            'marketGroupID as marketGroup',
        'FROM',
            'invTypes,',
            'invGroups,',
            'invCategories',
        'WHERE',
            'invTypes.groupID == invGroups.groupID',
            'AND invGroups.categoryID == invCategories.categoryID',
            'AND typeID == $id'
    ].join(' '),
    
    LIST_ITEMS: [
        'SELECT',
            'typeID AS id,',
            'typeName AS name,',
            'invTypes.description,',
            'invGroups.groupName AS type,',
            'invCategories.categoryName AS category,',
            'marketGroupID as marketGroup',
        'FROM',
            'invTypes,',
            'invGroups,',
            'invCategories',
        'WHERE',
            'invTypes.groupID == invGroups.groupID',
            'AND invGroups.categoryID == invCategories.categoryID'
    ].join(' '),
    
    SEARCH_ITEMS: [
        'SELECT',
            'typeID AS id,',
            'typeName AS name,',
            'invTypes.description,',
            'invGroups.groupName AS type,',
            'invCategories.categoryName AS category,',
            'marketGroupID as marketGroup',
        'FROM',
            'invTypes,',
            'invGroups,',
            'invCategories',
        'WHERE',
            'invTypes.groupID == invGroups.groupID',
            'AND invGroups.categoryID == invCategories.categoryID',
            'AND typeName LIKE $q'
    ].join(' '),
    
    ATTRIBUTE_QUERY: [
        'SELECT',
            'dgmAttributeTypes.attributeID AS id,',
            'dgmAttributeTypes.attributeName AS name,',
            'dgmAttributeTypes.description AS description,',
            'dgmAttributeTypes.displayName AS displayName,',
            'dgmTypeAttributes.value AS value',
        'FROM',
            'dgmAttributeTypes,',
            'dgmTypeAttributes',
        'WHERE',
           'dgmAttributeTypes.attributeID = dgmTypeAttributes.attributeID',
           'AND published = 1',
           'AND dgmTypeAttributes.typeID = $id'
    ].join(' '),
        
    SKILL_QUERY: [
        'SELECT',
            'Skills.typeName AS name,',
            'SkillName.value AS id,',
            'SkillLevel.value AS requiredLevel,',
            'Skills.description AS description,',
            'SkillRank.value AS rank',
        'FROM',
            'invTypes AS Skills,',
            'dgmTypeAttributes AS SkillName,',
            'dgmTypeAttributes AS SkillLevel,',
            'dgmTypeAttributes AS SkillRank',
        'WHERE',
            'Skills.typeID == SkillName.value',
            'AND (',
                'SkillName.attributeID == 182  OR',
                'SkillName.attributeID == 183  OR',
                'SkillName.attributeID == 184  OR',
                'SkillName.attributeID == 1285 OR',
                'SkillName.attributeID == 1289 OR',
                'SkillName.attributeID == 1290',
            ')',
            'AND SkillLevel.typeID == SkillName.typeID',
            'AND (',
                'SkillLevel.attributeID == 277  OR',
                'SkillLevel.attributeID == 278  OR',
                'SkillLevel.attributeID == 279  OR',
                'SkillLevel.attributeID == 1286 OR',
                'SkillLevel.attributeID == 1287 OR',
                'SkillLevel.attributeID == 1288',
            ')',
            'AND (',
                '(SkillName.attributeID == 182  AND SkillLevel.attributeID == 277 ) OR',
                '(SkillName.attributeID == 183  AND SkillLevel.attributeID == 278 ) OR',
                '(SkillName.attributeID == 184  AND SkillLevel.attributeID == 279 ) OR',
                '(SkillName.attributeID == 1285 AND SkillLevel.attributeID == 1286) OR',
                '(SkillName.attributeID == 1289 AND SkillLevel.attributeID == 1287) OR',
                '(SkillName.attributeID == 1290 AND SkillLevel.attributeID == 1288)',
            ')',
            'AND SkillRank.typeID == SkillName.value',
            'AND SkillRank.attributeID == 275',
            'AND SkillName.typeID == $id'
    ].join(' '),
    
    MARKET_TREE: [
        'SELECT',
            'marketGroupID AS id,',
            'marketGroupName AS name,',
            'description',
        'FROM',
            'invmarketgroups',
        'WHERE',
            'parentGroupID IS $parentId'
    ].join(' '),
    
    MARKET_PATH: [
        'SELECT',
            'marketGroupID AS id,',
            'marketGroupName AS name,',
            'description,',
            'parentGroupID AS parent',
        'FROM',
            'invmarketgroups',
        'WHERE',
            'marketGroupID IS $id'
    ].join(' '),
    
    LIST_ITEMS: [
        'SELECT',
            'typeID AS id,',
            'typeName AS name,',
            'invTypes.description,',
            'invGroups.groupName AS type,',
            'invCategories.categoryName AS category,',
            'marketGroupID as marketGroup',
        'FROM',
            'invTypes,',
            'invGroups,',
            'invCategories',
        'WHERE',
            'invTypes.groupID == invGroups.groupID',
            'AND invGroups.categoryID == invCategories.categoryID'
    ].join(' ')
};